sudo: false
language: node_js
matrix:
  include:
  - node_js: "6"
    env: NPM_RUN_SCRIPT=test-standard-coverage
  - node_js: "5"
  - node_js: "4"
  - node_js: "0.12"
  - node_js: "0.10"
    env: NPM_INSTALL_PACKAGES=es6-promise
install:
- npm install
- if [ -n "$NPM_INSTALL_PACKAGES" ]; then npm install $NPM_INSTALL_PACKAGES; fi
script:
- npm run ${NPM_RUN_SCRIPT:-test}
